[frameserve-config]
fps = 22                 # FPS: only works for gige cameras

[mask]
mask = "/home/m/Dropbox/maze/video/images/mask.png"                   # Path to mask image

[bg_config]
#learning_coeff = 0.0                # Learning coefficient to update model of image background


[hsv_config]
## set by hand: min area=76, max area=600
#h_thresholds={min=0, max=235} #{min=+int, max=+int} Hue pass band
#s_thresholds={min=0, max=256} #{min=+int, max=+int} Saturation pass band # doesnt matter much, should be wide
#v_thresholds={min=75,  max=256}#{min=+int, max=+int} Value pass band # Vmin absolutely crucial!
#min_area=6#+double Minimum object area (pixels2)
#max_area=4000#+double Maximum object area (pixels2)
#dilate=4#+int Candidate object dilation kernel size (pixels)
#erode=2#+int Candidate object erosion kernel size (pixels)

# set by hand: min area=76, max area=600
h_thresholds={min=0, max=256} #{min=+int, max=+int} Hue pass band
s_thresholds={min=0, max=256} #{min=+int, max=+int} Saturation pass band # doesnt matter much, should be wide
v_thresholds={min=17,  max=78}#{min=+int, max=+int} Value pass band # Vmin absolutely crucial!
min_area=100#+double Minimum object area (pixels2)
max_area=10000#+double Maximum object area (pixels2)
dilate=4#+int Candidate object dilation kernel size (pixels)
erode=6#+int Candidate object erosion kernel size (pixels)

[kalman]
dt = 0.02
timeout = 0.0
sigma_accel = 273.0
sigma_noise = 7.0
tune=0
